/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package phosphor.sudoku.lib

import phosphor.sudoku.lib.constants.GRID_SIZE
import phosphor.sudoku.lib.constants.GRID_SIZE_SQUARE_ROOT
import phosphor.sudoku.lib.constants.MAX_DIGIT_INDEX
import phosphor.sudoku.lib.constants.MIN_DIGIT_INDEX
import phosphor.sudoku.lib.enums.Level
import phosphor.sudoku.lib.generator.Sudoku
import kotlin.random.Random
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }

    @Test
    fun testStepSize() {
        for (i in 0 until GRID_SIZE step GRID_SIZE_SQUARE_ROOT) {
            println(i)
        }
    }

    @Test
    fun divideByZero() {
        println((0 / GRID_SIZE_SQUARE_ROOT) * GRID_SIZE_SQUARE_ROOT)
    }

    @Test
    fun testSudokuLib() {
        Sudoku.Builder().setLevel(Level.JUNIOR).build().printGrid()
    }
}
